# Navigation Links
[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 20

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 30

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 40

[[main]]
  name = "CV"
  url = "files/CV-David Rigby.pdf"
  weight = 50
